-- Drop and recreate listings table

DROP TABLE IF EXISTS listings CASCADE;

CREATE TABLE listings (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price INTEGER NOT NULL,
  created TIMESTAMP,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  condition BOOLEAN NOT NULL DEFAULT TRUE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  niche_id INTEGER REFERENCES niche(id) ON DELETE CASCADE
);
